# Generated by Django 4.2.3 on 2023-07-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallmanager',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hallmanager',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hallmanager',
            name='phone',
        ),
        migrations.AddField(
            model_name='hallmanager',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hallmanager',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hallmanager',
            name='manager_ID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hallmanager',
            name='manager_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hallmanager',
            name='manager_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hallmanager',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hallmanager',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
