# Generated by Django 4.2.3 on 2023-07-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_hallmanager_email_remove_hallmanager_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hall',
        ),
    ]
