# Generated by Django 4.2.3 on 2023-07-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_hall_picture_alter_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='hall/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
