# Generated by Django 3.2 on 2023-07-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_hall_picture_hallimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hall/'),
        ),
    ]
