# Generated by Django 3.2 on 2023-07-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_hall_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='occupants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
