# Generated by Django 3.2 on 2023-07-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_student_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='floors',
        ),
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hall/image/'),
        ),
        migrations.AlterField(
            model_name='hallimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hall/carousel/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('4 in 1', '4 in 1')], default='4 in 1', max_length=20),
        ),
    ]
